### ISSUE TITLE
Validation error hangs nextflow pipeline instead of erroring out

### ISSUE THREAD

**Issue by ginakkiim** [uclahs-cds/public-tool-PipeVal#17]
Requires debugging

**Comment by tyamaguchi-ucla** [comment]
Gina will follow up on this with @jmlivingstone

**Comment by tyamaguchi-ucla** [comment]
@jmlivingstone are you still having the same issue?

**Comment by jmlivingstone** [comment]
Sorry for the delay - just checked this and yes this is still an issue. I think what is happening is that align-RNA isn't waiting for the output of the validation tool before starting to run other processes. So even though the validation step fails, the other process keeps running. With other tools (ie STAR), if they fail, the whole pipeline fails. Maybe they are sending some error code to nextflow ? I am going to change the workflow so that other processes aren't launched until validation is done, but I am not sure if this is the standard in all pipelines.

**Comment by jmlivingstone** [comment]
Hmm, actually making the subsequent processes dependent on the output of the run_validate process didn't stop it from hanging after failure.
[a8/053658] process > run_validate (4)   [100%] 4 of 4, failed: 2 ✘
[ad/ee13a5] process > align_RNA_STAR (1) [  0%] 0 of 1
[-        ] process > run_index_SAMtools -
[-        ] process > run_sha512sum      -
Execution cancelled -- Finishing pending tasks before exit

**Comment by tyamaguchi-ucla** [comment]
I think we can close this issue @jmlivingstone?
